export enum KafkaServer {
  KAFKA_AUTH_SERVER = "KAFKA_AUTH_SERVER",
  KAFKA_ACCOUNT_SERVER = "KAFKA_ACCOUNT_SERVER",
  KAFKA_GAME_SERVER = "KAFKA_GAME_SERVER",
}

export enum TcpServer {
  TCP_AUTH_SERVER = "TCP_AUTH_SERVER",
  TCP_ACCOUNT_SERVER = "TCP_ACCOUNT_SERVER",
  TCP_GAME_SERVER = "TCP_GAME_SERVER",
}